### ISSUE TITLE
contrib/**/deploy.sh needs to move to standard _scripts/deploy.sh

### ISSUE THREAD

**Issue by sgoings** [deis/postgres#16]
In order to make our releases as smooth as possible, I'd like for the travis deploy.sh script to be located in the same place in all the Deis v2 component repos. Right now that place is: __scripts/deploy.sh_

My version bump/release tool has problems with this repository because the travis deploy script lives in the contrib/*\* structure:

```
Entering 'database'
---------
[tag-all]  advancing travis build to push with IMAGE_PREFIX=deisci and VERSION=v2-alpha2
[tag-all]  _scripts/deploy.sh doesn't exist in repo: database
```

**Comment by technosophos** [comment]
@sgoings Is this ready for review?
