### ISSUE TITLE
Using IAM perms for DB stopped working in workflow v2.9.0

### ISSUE THREAD

**Issue by dmcnaught** [deis/postgres#184]
Looks like we're checking if the vars are not empty, instead of empty:
https://github.com/deis/postgres/compare/v2.2.5...v2.4.4#diff-aa1fb98afc438f3a92745a99a587b0acR33
https://github.com/deis/postgres/blob/1ef7a37d453c4d6d6e5cf14ff79a877c0d73f27a/rootfs/docker-entrypoint-initdb.d/001_setup_envdir.sh#L33
I'll open a PR with the fix.
Relates to:
https://github.com/deis/workflow/issues/712
https://github.com/deis/workflow-migration/issues/9

**Comment by bacongobbler** [comment]
closed via deis/postgres#186
