### ISSUE TITLE
Ship full backup to object storage at a regular interval

### ISSUE THREAD

**Issue by slack** [deis/postgres#32]
Should support on and off-cluster object storage.

Support configurable backup retention via `wal-e delete retain X` where X comes from the replication controller.

**Comment by bacongobbler** [comment]
Pretty sure we were closing this in favour of documenting how to back Minio with persistent storage, correct?

**Comment by slack** [comment]
No. All configurations will require S3 compatible storage.

That requirement can be satisfied by minio for dev/test or off-cluster S3 storage for production configurations. Which means the postgres component should, out of the box, ship backups to the configured object storage.
