### ISSUE TITLE
Support optional shipping to tertiary storage

### ISSUE THREAD

**Issue by slack** [deis/postgres#33]
Where primary object storage is on cluster (or same provider), support shipping a backup on an interval to tertiary storage.

**Comment by bacongobbler** [comment]
Pretty sure we were closing this in favour of documenting how to back Minio with persistent storage, correct?

**Comment by slack** [comment]
The feature here is to support shipping to optional off-cluster storage. So not really relevant to minio.

**Comment by bacongobbler** [comment]
closed via #46
