### ISSUE TITLE
Run docker build on all PR builds

### ISSUE THREAD

**Issue by arschles** [deis/postgres#37]
Similar to what builder does in its [.travis.yml file](https://github.com/deis/builder/blob/master/.travis.yml#L16), postgres should run `make ... docker-build` to ensure that the Dockerfile is correct

**Comment by bacongobbler** [comment]
[already done](https://github.com/deis/postgres/blob/master/.travis.yml#L14) :)

**Comment by arschles** [comment]
:100:
