### ISSUE TITLE
postgres Alpha Requirements

### ISSUE THREAD

**Issue by slack** [deis/postgres#5]
To prove out the deis v2 integration we need to cut a release of deis/postgres that:
- [x] Deployable to K8S: Service def, RC def, repository follows [standard Deis pattern](https://github.com/technosophos/prototype-repo)
- [x] Installable by Helm (opt)
- [x] Is useable by deis/workflow and deis/controller components
- [x] Installation instructions documented in README
- [x] Installation linked to alpha setup in deis/workflow

The implementation for alpha does not need:
- HA
- Backups
- Recovery

**Comment by rimusz** [comment]
:+1:

**Comment by rimusz** [comment]
we need a new chart `postgres-standalone` with rc, svc and secret to store db password
