### ISSUE TITLE
add "master" label to pod on the fly

### ISSUE THREAD

**Issue by technosophos** [deis/postgres#6]
Is it possible to add add a label like `master:true` to the pod spec on the fly? That would open up the opportunity to run minions as read-only slaves in the future.

/cc @atschabu

**Comment by bacongobbler** [comment]
Right now we don't use labels. We just boot them all and they [race for a key](https://github.com/deis/postgres/blob/master/rootfs/app/governor.py#L45). First one takes master. There's no way to run other instances as read-only slaves at the moment, but this is something that I would like to eventually see with some on-the-fly configuration.

I'll have to think about this in a follow-up [rewrite of governor](https://github.com/deis/postgres/issues/7).

**Comment by bacongobbler** [comment]
Closing as multi-pod postgres is not something we want to target for v2. See #24.
