### ISSUE TITLE
Proposal: containerize the development environment

### ISSUE THREAD

**Issue by krancour** [deis/postgres#8]
This is to lower the barrier to entry for hacking on Deis while also standardizing the development environment for all contributors.

**Comment by arschles** [comment]
@krancour possibly overkill but I do a lot of my development in a container. explained in this post: https://medium.com/iron-io-blog/the-easiest-way-to-develop-with-go-introducing-a-docker-based-go-tool-c456238507d6

**Comment by bacongobbler** [comment]
This is irrelevant to postgres at the moment as there is nothing to compile. It's all shell.
