### ISSUE TITLE
wal-e restore errors on GCS

### ISSUE THREAD

**Issue by mboersma** [deis/postgres#94]
When object storage is pointed at GCS, trying to recover the platform shows errors in wal-e, specifically

```
lzop: <stdin>: not a lzop file
```

A valid backup may be restored, but wal-e may find the wrong generation of data apparently. So the situation is difficult to discern because apps may appear to completely or partially restored through the controller.

See the gory details at https://gist.github.com/mboersma/90799b42d29375fdcf0f7ddf4c5bc17e

**Comment by bacongobbler** [comment]
ping @kmala, any thoughts?

**Comment by kmala** [comment]
i think the error `lzop: <stdin>: not a lzop file` occurs because wal-e tries to find backup files one after the other until it doesn't find a file and assumes it is the end of backups because of which this is printed in the log as nothing got downloaded.I assume this error should be printed for other storage type also not just gcs.

**Comment by bacongobbler** [comment]
Sorry, I was more referring to if you know any case where using GCS as the backend would fail to replay or fetch WAL logs as opposed to other storage backends. For example, I think GCS is the only one that [refreshes an oauth2 token every so often](https://gist.github.com/mboersma/90799b42d29375fdcf0f7ddf4c5bc17e#file-wal-e-restore-log-L99-L100). I doubt that has anything to do with the problem, but I would like to dig into this and determine if there is an issue in the client that we can work around or if this is truly a blocker for the beta3 release, since recoverability is one of our targets for this release.

**Comment by mboersma** [comment]
Also in case I wasn't clear initially, this (or some other behavior) does have the end-user effect of restoring the wrong apps.

For example, I destroyed three apps and created a new one. Then after a recovery I had the original three. Or: once I did a recovery with an app that hadn't deployed yet, so no build or release to recover. After successful builds existed, I still could not coerce a recovery into finding the most recent backup, although I had watched wal-e succeed at backing up multiple segments after deploys.

**Comment by mboersma** [comment]
Also I couldn't make any of the above happen using Amazon S3, so it does appear to be specific to Google storage.

**Comment by bacongobbler** [comment]
To add to this with my own reproduction steps, I was able to recover quite nicely using vagrant and GCS:

```
><> deis apps
=== Apps
go
foo
bar
><> deis releases -a foo
=== foo Releases
v1      2016-04-28T15:11:57Z    bacongobbler created initial release
><> deis releases -a go
=== go Releases
v2      2016-04-28T15:09:58Z    bacongobbler deployed 779ca3d
v1      2016-04-28T15:05:17Z    bacongobbler created initial release
><> deis releases -a bar
=== bar Releases
v2      2016-04-28T15:12:52Z    bacongobbler deployed 779ca3d
v1      2016-04-28T15:12:19Z    bacongobbler created initial release
```

This is still a concern but I think it's ok to ship it and try to get feedback on how this bug would occur.

In the future, let's try the following:
- get the logs from database
- `helm uninstall workflow-beta3 -n deis`
- `helm install workflow-beta3`
- observe logs from database

We should see something like this if all is well: https://gist.github.com/bacongobbler/fa8035f22908d3968d569e2c6fa75879

**Comment by kmala** [comment]
I had tested the same on a GKE+GCS cluster setup and was able to successfully recover

**Comment by mboersma** [comment]
This was reproducible for me but seems isolated, so I'm moving it to beta4 for a resolution.

**Comment by bacongobbler** [comment]
To note, this is not a GCS-specific issue, but it occurs with all restores on occasion. I could not get to this for beta4 but it is my top priority for rc1 to figure out a solution via #95 or by other means.

**Comment by bacongobbler** [comment]
2 days of debugging this on vagrant, standalone (using the integration tests), AWS and GCE with S3 and GCS and I still cannot seem to reproduce this issue. This is still a concern, but if anyone's able to reproduce, please make sure to post logs here.

**Comment by bacongobbler** [comment]
punting to 2.0

**Comment by krancour** [comment]
I've observed that if I restore from backup, everything goes fine.  If I then make more additions to the database (e.g. create more apps or make app config changes), a subsequent attempt to restore from backup returns me to the same state as that initial restore.

I think that could possibly be related to this issue.

**Comment by bacongobbler** [comment]
@krancour I think you found our smoking gun. When I restored from my first backup, all was fine. However, the second and subsequent backups restored back to the initial backup, losing all new data.

Logs from "old" (read: first restoration after creating a few apps) database, saving up to `00000002000000000000000B.lzo`: https://gist.github.com/bacongobbler/44b99684fc0b7c8b7bd34881020f204f

And the logs from the database restoration, restoring up to `000000010000000000000008.lzo` (notice the `1` as it relates to the first historical backup): https://gist.github.com/bacongobbler/6bf9a4b701dfd755a093a1496a042c21

Notice that the restore logs cannot find [the history](https://gist.github.com/bacongobbler/6bf9a4b701dfd755a093a1496a042c21#file-gistfile1-txt-L266) [files](https://gist.github.com/bacongobbler/6bf9a4b701dfd755a093a1496a042c21#file-gistfile1-txt-L286). These are not present in S3, so I imagine this is significant.

**Comment by bacongobbler** [comment]
fix to the problem here: https://github.com/wal-e/wal-e/issues/229#issuecomment-203183909
